# This config file is used by ros2_control
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    TurtleArm_controller:
      type: joint_trajectory_controller/JointTrajectoryController


    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

TurtleArm_controller:
  ros__parameters:
    joints:
      - axis1_joint
      - axis2_joint
      - axis3_joint
      - axis4_joint
      - axisG_joint
    command_interfaces:
      []
    state_interfaces:
      []